system.forceSearchAttributesCacheRefreshOnRead:
  - value: true # Dev setup only. Please don't turn this on in production.
    constraints: {}
system.enableActivityEagerExecution:
  - value: true
frontend.enableUpdateWorkflowExecution:
  - value: true
frontend.enableUpdateWorkflowExecutionAsyncAccepted:
  - value: true
frontend.enableExecuteMultiOperation:
  - value: true
system.enableEagerWorkflowStart:
  - value: true
frontend.workerVersioningRuleAPIs:
  - value: true
frontend.workerVersioningDataAPIs:
  - value: true
frontend.workerVersioningWorkflowAPIs:
  - value: true
system.enableDeployments:
  - value: true
worker.buildIdScavengerEnabled:
  - value: true
worker.removableBuildIdDurationSinceDefault:
  - value: 1
system.enableNexus:
  - value: true
component.nexusoperations.callback.endpoint.template:
  - value: http://localhost:7243/namespaces/{{.NamespaceName}}/nexus/callback
# SDK tests use arbitrary callback URLs, permit that on the server.
component.callbacks.allowedAddresses:
  - value:
    - Pattern: "*"
      AllowInsecure: true
