version: "3.5"

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    networks:
      services-network:
        aliases:
          - cassandra

  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "8080:80"
      - "2003:2003"
      - "8125:8125"
      - "8126:8126"
    networks:
      services-network:
        aliases:
          - statsd

  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "STATSD_ENDPOINT=statsd:8125"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
      - statsd
    networks:
      services-network:
        aliases:
          - cadence

  integ-test:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    environment:
      - "SERVICE_ADDR=cadence:7933"
      - "GO111MODULE=on"
    depends_on:
      - cadence
    volumes:
      - ../../:/go/src/go.temporal.io/temporal
    networks:
      services-network:
        aliases:
          - integ-test

  unit-test:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    environment:
      - "GO111MODULE=on"
    volumes:
      - ../../:/go/src/go.temporal.io/temporal
    networks:
      services-network:
        aliases:
          - unit-test

  coverage-report:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    environment:
      - CI
      - BUILDKITE
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_TAG
      - BUILDKITE_REPO
      - BUILDKITE_BUILD_CREATOR
      - BUILDKITE_BUILD_CREATOR_EMAIL
      - BUILDKITE_BUILD_CREATOR_TEAMS
      - BUILDKITE_PULL_REQUEST_REPO
      - COVERALLS_TOKEN
      - "GO111MODULE=on"
    volumes:
      - ../../:/go/src/go.temporal.io/temporal
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent

networks:
  services-network:
    name: services-network
    driver: bridge
