version: "3.5"

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    networks:
      services-network:
        aliases:
          - cassandra

  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
      - "7234:7234"
      - "7235:7235"
      - "7239:7239"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
    networks:
      services-network:
        aliases:
          - temporal

  integ-test-zero-cache:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - |
        make integ_test_zero_cache
    environment:
      - "SERVICE_ADDR=temporal:7233"
      - "GO111MODULE=on"
    depends_on:
      - temporal
    volumes:
      - ../../:/go/src/go.temporal.io/sdk
    networks:
      services-network:
        aliases:
          - integ-test-zero-cache

  integ-test-sticky-on:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - |
        make integ_test_sticky_on
    environment:
      - "SERVICE_ADDR=temporal:7233"
      - "GO111MODULE=on"
    depends_on:
      - temporal
    volumes:
      - ../../:/go/src/go.temporal.io/sdk
    networks:
      services-network:
        aliases:
          - integ-test-sticky-on

  unit-test:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - |
        make unit_test
    environment:
      - "GO111MODULE=on"
    volumes:
      - ../../:/go/src/go.temporal.io/sdk
    networks:
      services-network:
        aliases:
          - unit-test

  coverage-report:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - |
        make .build/coverage/cover.out
    environment:
      - "GO111MODULE=on"
    volumes:
      - ../../:/go/src/go.temporal.io/sdk

networks:
  services-network:
    name: services-network
    driver: bridge
